galaxy_info:
  author: your_name
  description: Installs ArgoCD on Kubernetes
  company: your_company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - kubernetes
    - argocd
    - gitops

dependencies: []
